### PR TITLE
Add SHA256 and signature download links

### PR DESCRIPTION
**Pull request by MichaIng**
I built the website to test URL. It is functional, but probably looks a little crowded now. I'm open for suggestions about how to enhance the style, but IMO nothing urgent.

### CODE REVIEW

**Comment by ravenclaw900** [comment]
For me, only testing on mobile, all the checksums are downloading as [image name].xz.sha256.xz. I don't think the extra xz extension should be there.

**Comment by MichaIng** [comment]
Strange, this must be some dumb magic of your mobile browser then. Works as expected here and I double checked the links on test URL as well as in the HTML source document, and there is not a single `sha256.xz` string 🤔. Can you copy/share the SHA256 URL from the browser to double check it really has the `.xz` extension?

**Comment by MichaIng** [comment]
Ah I see the issue:
```
Content-Type: application/x-xz
```
Hmm, when I check this locally via `curl -kI 127.0.0.1`, I get `text/html` (`text/plain` would be better), so probably Cloudflare is doing this.

**Comment by MichaIng** [comment]
The `.asc` files currently have `application/pgp-keys` MIME type. Should be `application/pgp-signature` or just plain test: https://datatracker.ietf.org/doc/rfc3156/

The signature MIME seems to be used for encrypted/signed messaging via "OpenPGP Message Format", so it probably does not make sense for our download signatures, but shouldn't hurt either.

**Comment by MichaIng** [comment]
Okay fixed. Cloudflare respects MIME types explicitly defined on our server, I guess everything that it not `text/html` (fallback it seems).

No idea why Cloudflare assigns an `xz` MIME type is only any `.xz` appears in the middle of the URL. Doesn't make sense to me to ignore the actual file ending.

**Pull request merged**
