### PR TITLE
Add Orange Pi 5 to download page

### PR DESCRIPTION
**Pull request by danielpinto8zz6**

### CODE REVIEW

**Comment by ravenclaw900** [comment]
2 small things: One, the image needs to be sized 640x400. Second, could you try compressing the image with https://tinypng.com to shrink it down?

**Comment by danielpinto8zz6** [comment]
sure, will do it tomorrow

**Comment by MichaIng** [comment]
It needs to be 640x400, not 600x400 😉. This is only relevant here btw, not in the docs (so there it can stay as it is). Compression is not necessarily required since ImgBot does this automatically, at least losslessly.

**Comment by MichaIng** [comment]
All good, however, we need to wait until DietPi v8.14 release before merging, so that we can provide those images with stable DietPi `master` branch applied, instead of `dev` branch.

**Pull request merged**
