### PR TITLE
Bring dietpi-software.html to the same level as documentation

### PR DESCRIPTION
**Pull request by JappeHallunken**
- Added missing software, incl. short description etc
- Removed some titles from the page which were already removed from DietPi
- Added missing images
- Replaced some images
- Updated IDs, image alt tags and other minor fixes and improvements

### CODE REVIEW

**Comment by MichaIng** [comment]
Awesome! Many thanks for your hard work, including all the logos/images! 👍
I'll resolve the conflicts.

**Comment by MichaIng** [comment]
@JappeHallunken 
Can you grant me push permissions, respectively allow maintainer edits?

**Comment by MichaIng** [comment]
@JappeHallunken 
I'm still not able to push to the branch. Can you remove it from "protected branches"?

**Comment by JappeHallunken** [comment]
You should be able now to push.

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
Okay looks all great to me now. CI is all happy. Added a check for obsolete images which revealed some wrong URLs and old images we do not use anymore.

**Comment by ravenclaw900** [comment]
I'm really not that good at designing art (hence why I have a CSS framework handling most of the frontend design). I'd be fine with some sort of contest to decide what the new logo would be.

**Comment by MichaIng** [comment]
> I'm really not that good at designing art

Dito 😄. No that it would be something important, just an idea that came to my mind when I saw that Jappe created a plain text image for this and other software titles that do not have a logo.

Not related to this PR anyway, merging now.

**Pull request merged**
