### PR TITLE
Change contribute to donate and add logos for donation buttons!

### PR DESCRIPTION
**Pull request by Anulo2**
This PR should close both https://github.com/MichaIng/DietPi-Website/issues/76 and https://github.com/MichaIng/DietPi-Website/issues/135

### CODE REVIEW

**Comment by MichaIng** [comment]
Nice one, many thanks!

Not sure whether we should change the name of the HTML document (`contribute.html` => `donate.html`), to not break possibly existing links, and also obsolete search engine entries?

@StephanStS @Joulinar 
Are you fine with changing the menu text to "DONATE" only, or shall we use something like "DONATE/CONTRIBUTE" instead?

**Comment by Joulinar** [comment]
@MichaIng 
DONATE should be fine I guess.

**Comment by Anulo2** [comment]
So should I rollback to contribute.html or is this considered ready to be merged?

**Comment by Anulo2** [comment]
hey @MichaIng any update on this?

**Comment by MichaIng** [comment]
Sorry for the delay: Please revert renaming the `contribute.html` file. This is linked in various places across our website, docs, forum, and externally. However, having it renamed in the menu and the nice new texts/logos on the page are great.

@StephanStS 
You can generate the page just now, as you can set not only the branch but also the Git owner on our deployment trigger page 🙂.

**Comment by Anulo2** [comment]
Fixed thanks! Never noticed the missing gap since firefox adds automatically a whitespice (adding a gap too). Should be fixed. Also now the 2 boxes are the same size and works nicely on mobile too!

**Comment by StephanStS** [comment]
@MichaIng: Could you check the html checker output? 
https://github.com/MichaIng/DietPi-Website/actions/runs/7102775771/job/19333927909?pr=297

**Comment by StephanStS** [comment]
@MichaIng: The html checker complains about the new .svg files. Shall we exchange them with .png?

**Comment by MichaIng** [comment]
I'll minify them, which removes all the metadata that cause the errors.

**Pull request merged**
