### PR TITLE
Color palette changes

### PR DESCRIPTION
**Pull request by MichaIng**

### CODE REVIEW

**Review by fpetru — COMMENTED** [review]
It looks very good - well done @fn753 !

What I would suggest to make this PR available in live system few days after the DietPi release. In this way we could more clearly identify the users' response to this change (more like an A/B test). 

Furthermore I would suggest committing the change at once with a PR for DietPi-Docs. I suspect MkDocs theme being quite flexible to accommodate new color codes in an easy way.

**Comment by StephanStS** [comment]
A review is difficult for me without seeing it preliminarily.
I propose to merge this PR, then built a preliminary (test) site and check it.

**Comment by MichaIng** [comment]
No need to merge into dev, you can deploy the dev-color branch to the test URL as well.

**Comment by StephanStS** [comment]
> No need to merge into dev, you can deploy the dev-color branch to the test URL as well.

Yes, good idea! This I did not memorize. I will do that.

**Comment by fpetru** [comment]
> A review is difficult for me without seeing it preliminarily.
> I propose to merge this PR, then built a preliminary (test) site and check it.

@StephanStS - Try now the test

**Comment by StephanStS** [comment]
> > A review is difficult for me without seeing it preliminarily.
> > I propose to merge this PR, then built a preliminary (test) site and check it.
> 
> @StephanStS - Try now the test

I also did the trigger already (I did it in parallel to you, I hope I did it right), but I don't see any difference.

**Comment by MichaIng** [comment]
Try to reload the page with F5 or CTRL+F5 to trigger the browser validating or clearing the cache respectively.

**Comment by fn753** [comment]
I now saw that the button style isn't the same - some are rounded, some are not and the buttons in the slider look completely different.

**Comment by StephanStS** [comment]
> Try to reload the page with F5 or CTRL+F5 to trigger the browser validating or clearing the cache respectively.

I did that without success, also in a different browser, but actually the design is the new one. :-)
Another option, which I did not test, would have been to open a "private window". But I had not this idea. :-(

**Comment by MichaIng** [comment]
> but actually the design is the new one. :-)

But then it did work, or what is missing?

**Comment by StephanStS** [comment]
I saw this which should be corrected, or is it already done?
grafik

**Comment by MichaIng** [comment]
Saw it as well. Text colour needs to be changed to white.

**Comment by MichaIng** [comment]
Btw, currently the slider styles are overridden by our `style.css`, as first I wanted to keep the original `jquery.cslider.css` untouched. But that is not developed anymore, so I think it's time to move all related styles from `style.css` into `jquery.cslider.css`, or depending on size, everything into `style.css`. But no need to rush this, just FYI that it is okay to edit `jquery.cslider.css` and remove the overrides from `style.css` instead.

**Pull request merged**
