### PR TITLE
Initial stats & comparison page draft

### PR DESCRIPTION
**Pull request by MichaIng**
We may enhance the [script](https://github.com/MichaIng/hacks/blob/main/dietpi-distro_comparison) a bit, e.g. it makes sense to merge root and boot disk usage, check swap file size before removing it and to have it optionally creating the HTML block required for page? 🙂

Styles in `<head>` will move into `styles.css`, but while experimenting it's easier to have it in the header for now.

### CODE REVIEW

**Comment by MichaIng** [comment]
Ideen:
- Highlight/colour smaller (better) value, green vs red or similar, which suites colour scheme
- Remove commands, instead make an own tile containing the commands, used for each stat, and the script as well
- Bar charts and/or percentages to visualise comparison better
- Make tabs OS selectors with each multiple hardware tiles
- Use or merge OS/distro logo into tiles
- Sort stats by importance

**Comment by MichaIng** [comment]
Second feedback round:
- [ ] Add additional column between "DietPi" and compared OS for "DietPi / <compared OS>" percentage as DietPi divided by compared OS.
- [ ] Use a slightly brighter red for the "looser" and the code tags.
- [ ] Add distro logos
- [ ] Add all data we do already have

Bar charts are added in a dedicated round, as we need to think a little more about how to add them nicely.

**Comment by MichaIng** [comment]
Ready from my end. Please have a final look (test URL), also note the additional button in the features section below the title.

**Comment by Joulinar** [comment]
do we need an additional comparison for RPi OS 64bit?

**Comment by MichaIng** [comment]
Would be great indeed. Pinging @fpetru and @StephanStS here, so there is no doubled comparison done. I suggest the first one who actually starts doing this leaves a post here to inform the others 🙂.

**Comment by Joulinar** [comment]
I can do that. RPi3B+ or RPi4b 8GB?

**Comment by MichaIng** [comment]
RPi 4 would be better I think, as this is what most users nowadays have.

**Comment by Joulinar** [comment]
is that output ok?

```
root@DietPi:~# curl -L https://raw.githubusercontent.com/MichaIng/hacks/main/dietpi-distro_comparison | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3756  100  3756    0     0  45253      0 --:--:-- --:--:-- --:--:-- 45253
/ filesystem disk usage: "findmnt -nbo USED /"
524701696 bytes
/boot filesystem disk usage: "findmnt -nbo USED /boot"
32526848 bytes
Total disk usage:
531 MiB

Total memory usage: "free -th | mawk '/^Total:/{print $3}'"
43Mi

Number of pre-installed DEB packages: "dpkg --get-selections | wc -l"
228

Number of running processes: "echo $(( $(pstree -Ta | wc -l) - 3 ))" (minus echo, pstree and wc)
12

Boot duration: "systemd-analyze | mawk '{print $(NF-1)" "$NF;exit}'"
= 17.836s

/tmp is a tmpfs, which is good to reduce disk I/O.

/var/log is a tmpfs, which is good to reduce disk I/O, but logs are lost on system crash.

This image comes with an SSH server pre-installed.
The script was executed from within an SSH session, which increases the process count above by one, compared to a local console session.
Assure to run the script via SSH as well on other systems you want to compare.

root@DietPi:~#
```

**Comment by MichaIng** [comment]
> switched to Static IP. Boot duration changed from 17.836s to 9.852s 😉

Since RPi OS most likely uses DHCP as well, I think it's fair to compare against our unmodified image with DHCP, what you think?

And to avoid two additional processes + their memory usage, could you run those test with the script sourced?
```sh
curl -sSfLO https://raw.githubusercontent.com/MichaIng/hacks/main/dietpi-distro_comparison
. ./dietpi-distro_comparison
```
Yes it reboots on first execution intentionally to assure that everything is at a clean state and new kernel loaded after APT upgrade, in case.

**Comment by Joulinar** [comment]
ok will run the script again, flashing RPi OS 64bit atm

**Comment by MichaIng** [comment]
Okay, before you flash back and forth, I think it's fine when you run the script on RPi OS just the same way (curl | bash pipe). Thanks to GitHub edit memory, also the old boot time with DHCP is still there 🙂. Most importantly both distros are tested the same way, whether there is one expected process more or less is then not so important IMO, when it's the same on both.

**Comment by Joulinar** [comment]
I have too many free SD card since I switched to USB boot for my testing devices 🤣 

Will run both the same way and update the original post with both results

**Comment by MichaIng** [comment]
I'll merge this now.

**Pull request merged**
