### PR TITLE
Offer uncompressed ISO and ISO images for VMs

### PR DESCRIPTION
**Pull request by MichaIng**
For easier/alternative import to Proxmox and other VMs, installer ISO images are provided along with VM appliances and virtual disk images. And ISOs are now provided uncompressed. This is needed to directly import to Proxmox, instead of downloading separately first, then uncompromising. And on Roon forum, someone failed to setup a UEFI system, trying to flash the `xz` file directly, which does neither work with BelanaEtcher, nor with Rufus. The size is only minimally larger, as ISOs themselves are compressed already.

Do you think these are provided fine like this (test page), or should text or layout chance, or some explaining sentence below? In some other cases, we have 1-2 sentences in smaller text below each alternative download, to explain it. Not sure whether it makes sense as well here.

### CODE REVIEW

**Comment by StephanStS** [comment]
In my opinion, the description extension within the docs should be sufficient.
See related https://github.com/MichaIng/DietPi-Docs/issues/1036.

**Review by StephanStS — APPROVED** [review]

**Comment by StephanStS** [comment]
@MichaIng: Don't forget to move the files (e.g. [DietPi_VM-x86_64-Bookworm_Installer.iso](https://dietpi.com/downloads/images/testing/DietPi_VM-x86_64-Bookworm_Installer.iso)) from the [testing directory](https://dietpi.com/downloads/images/testing) to https://dietpi.com/downloads/images/

**Comment by MichaIng** [comment]
Already done :)

**Comment by MichaIng** [comment]
Already done for the ISOs. But indeed I can move the other new VM images as well, that were built along with the ISOs.

**Pull request merged**
