### PR TITLE
Typo on download link

### PR DESCRIPTION
**Pull request by Joulinar**
Typo on download link for NanoPiM4V2

### CODE REVIEW

**Comment by Joulinar** [comment]
Ah shit I guess you already corrected it? I was playing to long with Git Desktop App to create a PR, but was not working. Si need to go back to Github.com. 😃

**Comment by MichaIng** [comment]
Yes, fixed already: https://github.com/MichaIng/DietPi-Website/commit/ac7f172fbe387b95c0446b6aa726067cc02ba3db
However it seems the PR can be merged since the code matches 100%.

**Comment by MichaIng** [comment]
Strange, I rebased and merged, but the commit does not appear in the master branch history. Instead what has been "remerged" (?) is my own commit from 14h ago, still shown correctly in commit history:
> [MichaIng](https://github.com/MichaIng) merged commit [ac7f172](https://github.com/MichaIng/DietPi-Website/commit/ac7f172fbe387b95c0446b6aa726067cc02ba3db) into master 4 minutes ago

Interesting to observe irrelevant but unexpected behaviour of GitHub here 😄.

**Comment by Joulinar** [comment]
yeah as long as it's fixed 🤣 

at least the PR helped to figure out the using Github Desktop App is not something not working for me as it's not creating PR's. Instead it's trying to merge directly into the branch. Or I did it wrong way. 🤔

**Pull request merged**
